// Bakes the game's icon set from game-icons.net into one TypeScript module.
//
// Why bake rather than fetch at runtime: the icons become part of the bundle,
// so there is no network dependency, no flash of missing glyph, and the whole
// set is version-controlled alongside the code that names it.
//
// The source SVGs are 512x512 with a black background rect followed by the
// glyph as a white path. We keep only the glyph and drop the fill entirely, so
// the path inherits `currentColor` — which is what lets one icon be gold on the
// action bar, red on a cooldown and rarity-coloured in the bag without any of
// them needing their own copy.
//
// Usage:
//   node tools/art/icons.mjs           # validate + write
//   node tools/art/icons.mjs --check   # validate names only, write nothing

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ICON_MAP } from "./icon-map.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const OUT_TS = join(REPO, "client", "src", "ui", "icons.ts");
const OUT_CREDITS = join(REPO, "client", "public", "assets", "ICON_CREDITS.txt");
const CACHE = join(HERE, ".icon-cache");

const RAW = "https://raw.githubusercontent.com/game-icons/icons/master";
const TREE = "https://api.github.com/repos/game-icons/icons/git/trees/master?recursive=1";

const checkOnly = process.argv.includes("--check");

async function fetchIndex() {
  const cached = join(CACHE, "index.json");
  if (existsSync(cached)) return JSON.parse(readFileSync(cached, "utf8"));
  const res = await fetch(TREE);
  if (!res.ok) throw new Error(`icon index: HTTP ${res.status}`);
  const tree = await res.json();
  const names = tree.tree.filter((e) => e.path.endsWith(".svg")).map((e) => e.path.replace(/\.svg$/, ""));
  mkdirSync(CACHE, { recursive: true });
  writeFileSync(cached, JSON.stringify(names));
  return names;
}

/**
 * Every name is checked against the real index before a single file is
 * fetched. A mistyped icon name would otherwise fail silently — the glyph
 * simply would not be there — and finding which of a hundred keys is blank by
 * looking at the running game is exactly the kind of hunt worth designing out.
 */
function validate(index) {
  const known = new Set(index);
  const missing = [];
  for (const [key, path] of Object.entries(ICON_MAP)) {
    if (!known.has(path)) missing.push([key, path]);
  }
  if (missing.length === 0) return;

  console.error(`\n${missing.length} icon name(s) do not exist in game-icons:\n`);
  for (const [key, path] of missing) {
    const leaf = path.split("/")[1];
    // Suggest by leaf name, then by any word in it — a wrong author is by far
    // the commonest mistake and is trivially recoverable from the index.
    const byLeaf = index.filter((p) => p.split("/")[1] === leaf);
    const words = leaf.split("-").filter((w) => w.length > 2);
    const near = index.filter((p) => words.some((w) => p.split("/")[1].includes(w))).slice(0, 6);
    const hint = byLeaf.length ? byLeaf.join(", ") : near.length ? `near: ${near.join(", ")}` : "no suggestion";
    console.error(`  ${key.padEnd(20)} ${path.padEnd(38)} -> ${hint}`);
  }
  process.exit(1);
}

async function fetchIcon(path) {
  const cached = join(CACHE, path.replace("/", "__") + ".svg");
  if (existsSync(cached)) return readFileSync(cached, "utf8");
  const res = await fetch(`${RAW}/${path}.svg`);
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  const svg = await res.text();
  mkdirSync(CACHE, { recursive: true });
  writeFileSync(cached, svg);
  return svg;
}

/**
 * Pulls the glyph out of a source file. These all follow the same shape — a
 * background rect path, then the glyph — but the check is structural rather
 * than positional: we take the longest path, which is the drawing, never the
 * four-command rectangle behind it.
 */
function extractGlyph(svg, path) {
  const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
  if (ds.length === 0) throw new Error(`${path}: no path data`);
  const glyph = ds.reduce((a, b) => (b.length > a.length ? b : a));
  if (glyph.length < 40) throw new Error(`${path}: glyph suspiciously short`);
  return glyph;
}

const index = await fetchIndex();
validate(index);
console.log(`all ${Object.keys(ICON_MAP).length} icon names exist`);
if (checkOnly) process.exit(0);

const entries = [];
const authors = new Set();
for (const [key, path] of Object.entries(ICON_MAP)) {
  const glyph = extractGlyph(await fetchIcon(path), path);
  entries.push([key, glyph, path]);
  authors.add(path.split("/")[0]);
}

const body = entries.map(([key, d]) => `  ${JSON.stringify(key)}: ${JSON.stringify(d)},`).join("\n");

writeFileSync(
  OUT_TS,
  `// GENERATED by tools/art/icons.mjs — do not edit by hand.
// Source: game-icons.net (CC BY 3.0 / CC0), see client/public/assets/ICON_CREDITS.txt.
//
// One 512x512 path per icon, with no fill of its own so it takes \`currentColor\`
// from whatever is drawing it. Everything the interface used to say with an
// emoji says it with one of these instead.

export type IconKey =
${entries.map(([k]) => `  | ${JSON.stringify(k)}`).join("\n")};

export const ICON_PATHS: Record<IconKey, string> = {
${body}
};

export function hasIcon(key: string): key is IconKey {
  return key in ICON_PATHS;
}

/**
 * Markup for one icon. Sized by the element it lands in (\`width:100%\`) rather
 * than by a pixel size baked in here, so the same call serves a 40px bar slot
 * and a 14px inline label.
 */
export function iconSvg(key: string, className = "icon"): string {
  const d = ICON_PATHS[key as IconKey];
  if (!d) return "";
  return \`<svg class="\${className}" viewBox="0 0 512 512" aria-hidden="true"><path d="\${d}"/></svg>\`;
}

/**
 * Fills every data-icon element in a tree with its glyph.
 *
 * The static markup in index.html names its icons by key rather than carrying
 * the path data, which keeps the document small and means a re-map is a change
 * in this generated file rather than a hunt through the HTML. Idempotent, so it
 * is safe to call again after any markup is rebuilt.
 */
export function hydrateIcons(root: ParentNode = document): void {
  for (const el of Array.from(root.querySelectorAll<HTMLElement>("[data-icon]"))) {
    const key = el.dataset.icon;
    if (!key) continue;
    if (el.firstElementChild?.tagName.toLowerCase() === "svg") continue;
    el.innerHTML = iconSvg(key);
  }
}

/** Same icon as a real element, for the call sites that build DOM rather than strings. */
export function iconEl(key: string, className = "icon"): SVGSVGElement | null {
  const d = ICON_PATHS[key as IconKey];
  if (!d) return null;
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("class", className);
  svg.setAttribute("viewBox", "0 0 512 512");
  svg.setAttribute("aria-hidden", "true");
  const p = document.createElementNS("http://www.w3.org/2000/svg", "path");
  p.setAttribute("d", d);
  svg.appendChild(p);
  return svg;
}
`,
  "utf8",
);

writeFileSync(
  OUT_CREDITS,
  `Interface icons
===============

${entries.length} icons from game-icons.net, baked into client/src/ui/icons.ts by
tools/art/icons.mjs. Licensed CC BY 3.0 (some contributors release CC0); see
https://github.com/game-icons/icons/blob/master/license.txt for the per-author
terms.

Contributors whose work is used here:
${[...authors].sort().map((a) => `  - ${a}`).join("\n")}

Icon key -> source file:
${entries.map(([k, , p]) => `  ${k.padEnd(22)} ${p}.svg`).join("\n")}
`,
  "utf8",
);

console.log(`wrote ${entries.length} icons -> client/src/ui/icons.ts`);
console.log(`wrote credits -> client/public/assets/ICON_CREDITS.txt`);
